baseURL       = "/"
languageCode  = "en-us"
title         = "GLS Cycling | Cycling Race Team from the Great Lakes State"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Sponsors"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Results"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = ""
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "We’re a grassroots cycling team from the Great Lakes State"
    tagline               = "WE WORK HARD, WE PLAY HARD"
    primary_button        = "See Our Results"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "OUR LATEST ACTIVITY"
    subtitle  = "Join our club or follow us on Strava"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S RACE TOGETHER"
    primary_button      = "Clip-In"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "6800 Cannonsburg Rd"
      phone   = "555-555-5555"
      email   = "glscyclingteam@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "Sponsors"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Results"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Strava"
          url  = "https://www.strava.com/clubs/GLSCycling"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/glscycling/"
        [[params.footer.social.link]]
          name = "Twitter"
          url ="https://twitter.com/GLSCycling"
        [[params.footer.social.link]]
          name = "Facebook"
          url = "https://www.facebook.com/GLSCycling"
      # Footer Service
      [params.footer.service]
        title       = "We race bikes:"
        description = "gravel, fat, <br>mountain, and<br>virtual"
